[package]
name = "ngrammatic"
version = "0.4.0"
edition = "2021"
authors = ["Will Page <compenguy@gmail.com>"]
description = "Character-oriented ngram generator and fuzzy matching library."
homepage = "https://github.com/compenguy/ngrammatic"
repository = "https://github.com/compenguy/ngrammatic"
documentation = "https://docs.rs/ngrammatic"
readme = "README.md"
categories = ["text-processing"]
keywords = ["fuzzy", "ngrams", "shingles"]
license = "MIT"

[lib]
name = "ngrammatic"

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }
mem_dbg = { version = "0.1", optional = true }
sux = {git = "https://github.com/LucaCappelletti94/sux-rs.git"}
half = {version="2.4.0", optional = true, features = ["zerocopy"]}
rayon = {version="1.10.0", optional=true}
webgraph = {git="https://github.com/vigna/webgraph-rs.git", optional=true}

fxhash = "0.2.1"

[dev-dependencies]
flate2 = "1.0.28"
indicatif = "0.17.8"

[features]
serde = ["dep:serde", "half/serde"]

[profile.release]
overflow-checks = false   # Disable integer overflow checks.
debug = false            # Include debug info.
debug-assertions = false  # Enables debug assertions.
opt-level = 3
