[package]
name = "ngrammatic"
version = "0.5.0"
edition = "2021"
authors = ["Will Page <compenguy@gmail.com>", "Luca Cappelletti <luca@ironprism.com>"]
description = "Scalable n-gram generator for fuzzy similarity search with TF-IDF & efficient data structures."
homepage = "https://github.com/compenguy/ngrammatic"
repository = "https://github.com/compenguy/ngrammatic"
documentation = "https://docs.rs/ngrammatic"
readme = "README.md"
categories = ["algorithms", "text-processing", "data-structures"]
keywords = ["fuzzy", "ngrams", "shingles", "tf-idf", "search"]
license = "MIT"

[lib]
name = "ngrammatic"

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }
mem_dbg = { version = "0.2"}
sux = {git = "https://github.com/vigna/sux-rs.git", no-default-features = true}
half = {version="2.4.0", optional = true, features = ["zerocopy"]}
rayon = {version="1.10.0", optional=true}
webgraph = {git="https://github.com/vigna/webgraph-rs.git", branch="mem_dbg"}

fxhash = "0.2.1"
tempfile = "3.10.1"
dsi-bitstream = {git="https://github.com/vigna/dsi-bitstream-rs.git", features=["mem_dbg"]}
epserde = "0.6"
log = "0.4.21"
lender = "0.2.9"
rand = "0.8.5"

[dev-dependencies]
flate2 = "1.0.28"
indicatif = "0.17.8"
# We also use the version of the ngrammatic library before the refactoring
# to evaluate the changes in performance. The version we refer to is the 0.4.0
# version of the library.
ngrammatic_old = { version = "0.4.0", package="ngrammatic" }
paste = "1.0.14"

[features]
default = ["rayon"]
serde = ["dep:serde", "half/serde"]
rayon = ["dep:rayon", "sux/rayon"]

[profile.release]
overflow-checks = false   # Disable integer overflow checks.
debug = false            # Include debug info.
debug-assertions = false  # Enables debug assertions.
opt-level = 3
